In [1]:
import numpy as np
from src.data.preprocess.dataturks.preprocess_translearn_hatespeech import create_NN_sets
from src.evaluation.hatespeech.evaluation_translearn_hatespeech import evaluate_best_model
from src.models.hatespeech.model_translearn_hatespeech import fine_tune_model

np.random.seed(42)
vocab_size = 10000
path_to_target_data = "../../data/external/hatespeech/clean_sexism_dataset.csv"
path_to_original_model = "../../models/example_dataturks.h5"
path_to_fine_tuned_model = "../../models/fine_tuned.h5"
path_to_fine_tuned_model2 = "../../models/fine_tuned_last_layer.h5"
path_to_sexist_model = "../../models/zeerak_model.h5"

datasets = create_NN_sets(path_to_target_data, vocab_size)
# fine_tune_model(path_to_original_model, path_to_fine_tuned_model, datasets)
print("\n Evaluation of model with ALL layers fine-tuned:")
evaluate_best_model(path_to_fine_tuned_model, datasets[4], datasets[5], datasets[6], 10000)

# fine_tune_model(path_to_original_model, path_to_fine_tuned_model2, datasets)
print("\n Evaluation of model with LAST layer fine-tuned:")
evaluate_best_model(path_to_fine_tuned_model2, datasets[4], datasets[5], datasets[6], 10000)

# train_model(path_to_sexist_model, datasets, vocab_size)
print("\n Evaluation of model trained from scratch:")
evaluate_best_model(path_to_sexist_model, datasets[4], datasets[5], datasets[6], 10000)

Using TensorFlow backend.


Words in index: 22101

 Evaluation of model with ALL layers fine-tuned:
Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
2982/2982 [==============================] - 0s 72us/step
acc: 87.42%, loss: 0.34
Confusion matrix:
[[2181  139]
 [ 236  426]]
Marco F1:0.807606
Micro F1:0.874245
Weighted F1:0.870562

 Evaluation of model with LAST layer fine-tuned:
2982/2982 [==============================] - 0s 60us/step
acc: 87.22%, loss: 0.34
Confusion matrix:
[[2194  126]
 [ 255  407]]
Marco F1:0.800640
Micro F1:0.872233
Weighted F1:0.867065

 Evaluation of model trained from scratch:
2982/2982 [==============================] - 0s 61us/step
acc: 88.46%, loss: 0.29
Confusion matrix:
[[2216  104]
 [ 240  422]]
Marco F1:0.819205
Micro F1:0.884641
Weighted F1:0.879681
